<?php

# this will fill out the missing ending frame numbers (next start - 1) in override files

# also puts the suggested pattern from bogusscenes.txt, generated by 1.php, on a second run

$bogusscenes = [];

if(preg_match('/^(title_t[0-9]+[^-]*-)/i', $argv[1], $m)
|| preg_match('/^(S[0-9]+(E|R)[0-9]+-)/i', $argv[1], $m))
{
	$fn = $m[1].'bogusscenes.txt';
	
	if(file_exists($fn))
	{
		foreach(explode("\n", file_get_contents($fn)) as $row)
		{
			$row = trim($row);

			if(!preg_match('/^([0-9]+,[0-9]+).+# ([cpbnu]+)$/i', $row, $m)) continue;

			$bogusscenes[$m[1]] = $m[2];
		}
	}
}

$framenum = [];

$rows = explode("\n", file_get_contents($argv[1]));

foreach($rows as $i => $row)
{
	$row = trim($row);
	
	if(preg_match('/^([0-9]+)/i', $row, $m))
	{
		$framenum[$i] = (int)$m[1];
	}
}

foreach($rows as $i => $row)
{
	$row = trim($row);
	
	if(preg_match('/^([0-9]+)$/i', $row, $m))
	{
		for($j = $i + 1; $j < count($rows); $j++)
		{
			if(!isset($framenum[$j])) continue;

			$row .= ','.($framenum[$j] - 1);
			
			if(isset($bogusscenes[$row]))
			{
				$row .= ' '.$bogusscenes[$row].' # TODO ';
			}
			else
			{
				$row .= ' ';
			}
		
			break;
		}
	}
	else if(preg_match('/^([0-9]+,[0-9]+)$/i', $row, $m))
	{
		if(isset($bogusscenes[$row]))
		{
			$row .= ' '.$bogusscenes[$row].' # TODO';
		}
		else
		{
			$row .= ' ';
		}
	}
	
	echo $row.PHP_EOL;
}

?>